image:
  name: hashicorp/terraform:latest
  entrypoint: ["/bin/sh", "-c"]

stages:
  - init
  - plan
  - apply
  - destroy

variables:
  TF_STATE_NAME: "default"

terraform-init:
  stage: init
  script:
    - cd basic
    - terraform init
  artifacts:
    paths:
      - basic/.terraform/
      - basic/.terraform.lock.hcl
    expire_in: 1 hour

terraform-plan:
  stage: plan
  script:
    - cd basic
    - terraform plan
  needs:
    - job: terraform-init
      artifacts: true
  when: manual

terraform-apply:
  stage: apply
  script:
    - cd basic
    - terraform apply -auto-approve
  needs:
    - job: terraform-plan
      artifacts: true
  when: manual

terraform-destroy:
  stage: destroy
  script:
    - cd basic
    - terraform destroy -auto-approve
  needs:
    - job: terraform-init
      artifacts: true
  when: manual
