image:
  name: hashicorp/terraform:latest
  entrypoint: ["/bin/sh", "-c"]   # <-- IMPORTANT

stages:
  - init
  - plan
  - apply

terraform-init:
  stage: init
  script:
    - cd basic
    - terraform init
  when: on_success        # MUST run automatically (default)
  artifacts:
    paths:
      - basic/.terraform/
      - basic/.terraform.lock.hcl

terraform-plan:
  stage: plan
  script:
    - cd basic
    - terraform plan
  needs: ["terraform-init"]
  when: manual            # You trigger manually

terraform-apply:
  stage: apply
  script:
    - cd basic
    - terraform apply -auto-approve
  needs: ["terraform-plan"]
  when: manual            # You trigger manually
