image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

stages:
  - init
  - plan
  - apply

terraform-init:
  stage: init
  script:
    - cd basic
    - terraform init
  artifacts:
    paths:
      - basic/.terraform
      - basic/.terraform.lock.hcl
    expire_in: 1 hour
  when: on_success

terraform-plan:
  stage: plan
  script:
    - cd basic
    - terraform plan
  needs:
    - job: terraform-init
      artifacts: true
  when: manual

terraform-apply:
  stage: apply
  script:
    - cd basic
    - terraform apply -auto-approve
  needs:
    - job: terraform-plan
      artifacts: true
  when: manual
