image: hashicorp/terraform:latest

stages:
  - init
  - plan
  - apply

terraform-init:
  stage: init
  script:
    - cd "basic terra"
    - terraform init
  when: manual

terraform-plan:
  stage: plan
  script:
    - cd "basic terra"
    - terraform plan
  needs: ["terraform-init"]
  when: manual

terraform-apply:
  stage: apply
  script:
    - cd "basic terra"
    - terraform apply -auto-approve
  needs: ["terraform-plan"]
  when: manual
